### PR TITLE
Fix built-in elements inheritance

### LINKED ISSUE #62: extending built-in elements with a base class different than HyperHTMLElement doesn't work
Hi there!

I think I've come across an issue today, I would like your opinion!

Minimal reproduction:
```html
<!doctype html>
<html lang="en">
<head>
    <script type="text/javascript" src="https://unpkg.com/hyperhtml-element@3.11.0/min.js"></script>
</head>
<body>
<div id="root"></div>

<script type="text/javascript">

    class Base extends HyperHTMLElement{}

    class MyButtonOK extends HyperHTMLElement{
      created() {
        console.log(this.setState); //function :)
      }
    }

    class MyButtonErr extends Base{
      created() {
        console.log(this.setState); //undefined :(
      }
    }

    class StandaloneOk extends Base{
      created() {
        console.log(this.setState); //function :)
      }
    }

    MyButtonOK.define('my-button', {extends: 'button'});
    MyButtonErr.define('my-button-sad', {extends: 'button'});
    StandaloneOk.define('standalone-ok');

  HyperHTMLElement.bind(document.getElementById('root'))`
    <button is="my-button">this.setState is ok</button>
    <button is="my-button-sad">this.setState is undefined</button>
    <standalone-ok>this.setState is ok</standalone-ok>
    `;
</script>
</body>
</html>
```

The problem seems to be in this bit of code: https://github.com/WebReflection/hyperHTML-Element/blob/master/index.js#L2372

I think it's assuming that Super is going to be the HyperHTMLElement class. I got it fixed by including `ownKeys(HyperHTMLElement)`. I'll open a PR in a bit so you can have a look.

Thanks!

### PR DESCRIPTION
**Pull request by fsodano**
Due to built-in elements extending the standard HTML Classes,
there's a need to add `HyperHTMLElement`'s own class members as well.

`HyperHTMLElement` assumed the `Super` class was going to be itself,
this commit fixes that by explicitly adding `HyperHTMLElement`
own keys to the `Intermediate` class used to create our own built-in
element extension.

Fixes #62

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -2372,24 +2372,31 @@ var HyperHTMLElement = (function (exports) {
...
-            getOwnPropertyDescriptor(Super.prototype, key)
-          )
-        );
+        let Super, BaseClass = Class;
+        while(Super = getPrototypeOf(BaseClass)){
+          ownKeys(Super)
+            .filter(key => [
+              'length', 'name', 'arguments', 'caller', 'prototype'
+            ].indexOf(key) < 0)
+            .forEach(key => defineProperty(
```
Comment (WebReflection) [inline index.js]: as you go top down, you don't want to define overwrites so that the filter should also check that the property doesn't exist already in the `Intermediate` class. An easy way to do this, is to define the keys to filter outside the loop and add each key that wasn't there already.

```js
// example ...
const keys = ['length', 'name', 'arguments', 'caller', 'prototype'];
while(Super = getPrototypeOf(BaseClass)) {
  ownKeys(Super)
    .filter(key => keys.indexOf(key) < 0)
    .forEach(key => {
      keys.push(key);
      defineProperty(Intermediate, key, getOwnPropertyDescriptor(Super, key));
    })
}
```

In this way, if `B` has `method` and it was overwriting the `A` `method`, the `Intermediate` would get `B` and it will ignore `A`, I hope it's clear

Comment (fsodano) [reply index.js]: Very clear, thanks. I had to add it to both loops, so now that both loops do the same but for different targets, I simplified it into one loop.

Let me know what you think.

Thanks!

File: index.js [hunk 2]
```diff
@@ -2372,24 +2372,30 @@ var HyperHTMLElement = (function (exports) {
...
+        while (Super = getPrototypeOf(BaseClass)) {
+          [
+            {target: Intermediate, base: Super},
+            {target: Intermediate.prototype, base: Super.prototype}
+          ].forEach(({target, base}) => {
+              ownKeys(base)
+                .filter(key => keys.indexOf(key) < 0)
+                .forEach((key) => {
+                  keys.push(key);
+                  return defineProperty(
```
Comment (WebReflection) [inline index.js]: no need to return within a `forEach`

Comment (fsodano) [reply index.js]: Fixed, please have another look :)

**Comment by WebReflection** [comment]
First of all, thank you!

Secondly, this is landing as minor semver change, simply because it could cause undesired side-effects for those that trusted current behavior until now.

In few words, `hyperhtml-element@3.12.0` is out with these changes in, and I hope everything will work as expected 👋

**Comment by fsodano** [comment]
Awesome, thanks @WebReflection !

**Comment by fsodano** [comment]
@WebReflection one more: did I have to commit the results of `npm build`?
